name: Socks4
protocol: tcp
rarity: 8
payload: \x04\x01\x00\x16\x7f\x00\x00\x01root\x00
ports: 199,1080,1090,1095,1100,1105,1109,3128,6588,6660,6661,6662,6663,6664,6665,6666,6667,6668,6669,8000,8008,8080,8088
services:
    - name: socks4
      pattern:
        regex: ^\0\x5a
      info: Connection ok
    - name: socks4
      pattern:
        regex: ^\0\x5b
      info: Connection rejected or failed; connections possibly ok
    - name: socks4
      pattern:
        regex: ^\0\x5c
      info: Connection failed; ident required
    - name: socks4
      pattern:
        regex: ^\0\x5d
      info: Connection failed; username required
    - name: shell
      pattern:
        regex: ^\0Access is denied\n$
      product: Windows Services for Unix rsh
      os: Windows
      cpes:
        - a:microsoft:windows_services_for_unix
        - o:microsoft:windows
