name: SqueezeCenter
protocol: udp
rarity: 8
payload: eIPAD\0NAME\0JSON\0VERS\0UUID\0JVID\x06\x12\x34\x56\x78\x12\x34
ports: "3483"
services:
    - name: squeezecenter
      pattern:
        regex: ^ENAME.{1}(.+)JSON.{1}(\d+)VERS.{1}(.+)UUID.{1}(.+)$
      product: Logitech SqueezeCenter music server
      version: $3
      info: 'Server Name: $1, JSON: $2, UUID: $4'
