name: TerminalServerCookie
protocol: tcp
rarity: 7
payload: '\x03\0\0*%\xe0\0\0\0\0\0Cookie: mstshash=nmap\r\n\x01\0\x08\0\x03\0\0\0'
ports: 3388,3389
fallbacks: TerminalServer
services:
    - name: ms-wbt-server
      pattern:
        regex: ^\x03\0\0\x13\x0e\xd0\0\0\x124\0\x02[\x07\x0f\x1f]\x08\0\x02\0\0\0
      product: Microsoft Terminal Services
      os: Windows
      cpes:
        - o:microsoft:windows
    - name: ms-wbt-server
      pattern:
        regex: ^\x03\0\0\x0b\x06\xd0\0\0\x124\0$
      product: Microsoft Terminal Services
      os: Windows XP
      cpes:
        - o:microsoft:windows_xp
