name: LDAPSearchReqUDP
protocol: udp
rarity: 8
payload: \x30\x84\x00\x00\x00\x2d\x02\x01\x07\x63\x84\x00\x00\x00\x24\x04\x00\x0a\x01\x00\x0a\x01\x00\x02\x01\x00\x02\x01\x64\x01\x01\x00\x87\x0b\x6f\x62\x6a\x65\x63\x74\x43\x6c\x61\x73\x73\x30\x84\x00\x00\x00\x00
ports: "389"
services:
    - name: ldap
      pattern:
        regex: ^0\x84\0\0..\x02\x01.*dsServiceName1\x84\0\0\0.\x04.CN=NTDS\x20Settings,CN=([^,]+),CN=Servers,CN=([^,]+),CN=Sites,CN=Configuration,DC=([^,]+),DC=([^,]+)0\x84\0
        options: s
      product: Microsoft Windows Active Directory LDAP
      info: 'Domain: $3.$4, Site: $2'
      hostname: $1
      os: Windows
      cpes:
        - o:microsoft:windows
    - name: ldap
      pattern:
        regex: ^0\x84\0\0..\x02\x01.*dsServiceName1\x84\0\0\0.\x04.CN=NTDS\x20Settings,CN=([^,]+),CN=Servers,CN=([^,]+),CN=Sites,CN=Configuration,DC=([^,]+),DC=([^,]+),DC=([^,]+)0\x84\0
        options: s
      product: Microsoft Windows Active Directory LDAP
      info: 'Domain: $3.$4.$5, Site: $2'
      hostname: $1
      os: Windows
      cpes:
        - o:microsoft:windows
