name: Arucer
protocol: tcp
rarity: 8
payload: \xC2\xE5\xE5\xE5\x9E\xA0\xD7\xA4\xA6\xD0\xD5\xDD\xDC\xC8\xD6\xDD\xD7\xD5\xC8\xD1\xD6\x83\x80\xC8\xDD\xA4\xD1\xA1\xC8\xA4\xD2\xD5\xD7\xDD\xA3\xA4\xA1\xDD\xA6\xD7\xDD\x98\xE5
ports: "7777"
services:
    - name: arucer
      pattern:
        regex: ^\xbc\xa0\xb6$
      product: Arucer backdoor
      info: '**BACKDOOR**'
      os: Windows
      cpes:
        - o:microsoft:windows
