name: oracle-tns
protocol: tcp
rarity: 7
payload: \0Z\0\0\x01\0\0\0\x016\x01,\0\0\x08\0\x7F\xFF\x7F\x08\0\0\0\x01\0 \0:\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\04\xE6\0\0\0\x01\0\0\0\0\0\0\0\0(CONNECT_DATA=(COMMAND=version))
ports: 1035,1521,1522,1525,1526,1574,1748,1754,14238,20000
services:
    - name: http
      pattern:
        regex: '^HTTP/1\.0 400 Bad Request\r\nDate: .*\r\nServer: Boa/([\w._-]+)\r\nConnection: close\r\nContent-Type: text/html\r\n\r\n<HTML><HEAD><TITLE>400 Bad Request</TITLE></HEAD>\n<BODY><H1>400 Bad Request</H1>\nYour client has issued a malformed or illegal request\.\n</BODY></HTML>\n$'
      product: Boa httpd
      version: $1
      info: Prolink ADSL router
      device-type: broadband router
      cpes:
        - a:boa:boa:$1
    - name: iscsi
      pattern:
        regex: ^\x3f\x80\x04\0\0\0\x00\x30\0\0\0\0\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\xf7\0\0\0\0\0\0\0\0\0\0\0\0\0Z\0\0\x01\0\0\0\x016\x01\x2c\0\0\x08\0\x7f\xff\x7f\x08\0\0\0\x01\0\x20\0\x3a\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x004\xe6\0\0$
      product: iSCSI
    - name: iscsi
      pattern:
        regex: ^\x3f\x80\x04\0\0\0\x00\x30\0\0\0\0\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x00\x00\0\0\0\0\0\0\0\0\0\0\0\0\0Z\0\0\x01\0\0\0\x016\x01\x2c\0\0\x08\0\x7f\xff\x7f\x08\0\0\0\x01\0\x20\0\x3a\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x004\xe6\0\0$
      product: HP StorageWorks D2D backup system iSCSI
      device-type: storage-misc
    - name: palm-hotsync
      pattern:
        regex: ^\x01.\0\0\0\x14\x11\x01\0\0\0\0\0\0\0\x20\0\0\0\x06\x01\0..\0\0$
        options: s
      product: Palm Pilot HotSync
    - name: oracle-tns
      pattern:
        regex: '^\0.\0\0[\x02\x04]\0\0\0.*TNSLSNR for ([-.+/ \w]{2,24}): Version ([-\d.]+) - Production'
        options: s
      product: Oracle TNS Listener
      version: $2
      info: for $1
    - name: dbsnmp
      pattern:
        regex: ^\0.\0\0\x02\0\0\0.*\(IAGENT = \(AGENT_VERSION = ([\d.]+)\)\(RPC_VERSION = ([\d.]+)\)\)
        options: s
      product: Oracle Intelligent Agent
      version: $1
      info: RPC v$2
    - name: oracle
      pattern:
        regex: ^\0\x20\0\0\x02\0\0\0\x016\0\0\x08\0\x7f\xff\x01\0\0\0\0\x20
        options: s
      product: Oracle Database
      cpes:
        - a:oracle:database_server
    - name: oracle
      pattern:
        regex: ^\+\0\0\0$
      product: Oracle Database
      cpes:
        - a:oracle:database_server
    - name: oracle-tns
      pattern:
        regex: ^..\0\0\x04\0\0\0\"\0..\(DESCRIPTION=\(TMP=\)\(VSNNUM=\d+\)\(ERR=1189\)\(ERROR_STACK=\(ERROR=\(CODE=1189\)\(EMFI=4\)\)
      product: Oracle TNS Listener
      info: unauthorized
    - name: oracle-tns
      pattern:
        regex: ^..\0\0\x04\0\0\0\"\0..\(DESCRIPTION=\(TMP=\)\(VSNNUM=\d+\)\(ERR=1194\)\(ERROR_STACK=\(ERROR=\(CODE=1194\)\(EMFI=4\)\)\)\)
      product: Oracle TNS Listener
      info: insecure transport
    - name: oracle-tns
      pattern:
        regex: ^..\0\0\x04\0\0\0\"\0..\(DESCRIPTION=\(ERR=12504\)\)\0
      product: Oracle TNS listener
      info: requires service name
    - name: dbsnmp
      pattern:
        regex: ^\0,\0\0\x04\0\0\0\"\0\0 \(CONNECT_DATA=\(COMMAND=version\)\)
      product: Oracle DBSNMP
    - name: hp-radia
      pattern:
        regex: ^\xff\xff$
      product: HP Radia configuration server
    - name: winbox
      pattern:
        regex: ^.\x01\0.M2\x01\0\xff\x88\0\0\x02\0\xff\x88[\x01\x02]\0
        options: s
      product: MikroTik WinBox
      cpes:
        - a:mikrotik:winbox
    - name: wow
      pattern:
        regex: ^\0\0\t.{32}\x01..{32}
      product: World of Warcraft authserver
fallback-services:
    - name: oracle-tns
      pattern:
        regex: ^\0.\0\0[\x02\x04]\0\0\0.*\([ABD-Z]
        options: s
      product: Oracle TNS Listener
