name: memcached
protocol: udp
rarity: 8
payload: \0\x01\0\0\0\x01\0\0stats\r\n
ports: "11211"
services:
    - name: memcached
      pattern:
        regex: ^\0\x01\0\0\0\x01\0\0STAT pid \d+\r\nSTAT uptime \d+\r\nSTAT time \d+\r\nSTAT version ([.\d]+)\r\n
        options: s
      product: Memcached
      version: $1
      cpes:
        - a:memcached:memcached:$1
    - name: memcached
      pattern:
        regex: ^\0\x01\0\0\0\x01\0\0STAT pid \d+\r\nSTAT uptime \d+\r\nSTAT time \d+\r\nSTAT version ([.\d]+) \(?Ubuntu\)?\r\n
        options: s
      product: Memcached
      version: $1
      info: Ubuntu
      os: Linux
      cpes:
        - a:memcached:memcached:$1
        - o:canonical:ubuntu_linux
        - o:linux:linux_kernel
fallback-services:
    - name: memcached
      pattern:
        regex: '^\0\x01\0\0\0\x01\0\0STAT '
