name: Hello
protocol: tcp
rarity: 8
payload: EHLO\r\n
ports: 25,587,3025
ssl-ports: "465"
services:
    - name: exalead
      pattern:
        regex: ^\? 1 illegal command\n\0
      product: Exalead search appliance
    - name: smtp
      pattern:
        regex: ^220\s+(DP-\d+)\r\n250-Hello\r\n250-DSN\r\n
      product: Panasonic smtpd
      version: $1
      info: Panasonic printer
      device-type: printer
    - name: smtp
      pattern:
        regex: ^220 ESMTP service ready\r\n250\x20ok\r\n
      product: Rustock smtp backdoor
      info: '**BACKDOOR**'
      os: Windows
      cpes:
        - o:microsoft:windows
    - name: smtp
      pattern:
        regex: ^220 Hello [A-Z][a-z]{2}, .*\r\n501 Command \"EHLO\" requires an argument\r\n
      product: Lotus Notes smtpd
      cpes:
        - a:ibm:lotus_notes
    - name: smtp
      pattern:
        regex: ^220 ([\w_.-]+) ESMTP\r\n250-[-\w_.]+\r\n250-AUTH LOGIN CRAM-MD5 PLAIN\r\n250-AUTH=LOGIN CRAM-MD5 PLAIN\r\n250-PIPELINING\r\n250 8BITMIME\r\n
      product: Access Remote PC smtpd
      hostname: $1
      os: Windows
      cpes:
        - o:microsoft:windows
    - name: smtp
      pattern:
        regex: ^220 \[[\w_.-]+\] FTGate Server Ready\r\n250-([\w._-]+)\r\n
      product: Floosietek FTGate smtpd
      hostname: $1
      os: Windows
      cpes:
        - o:microsoft:windows
    - name: smtp
      pattern:
        regex: ^220 ([\w_.-]+) Ready\r\n250-.*\r\n250-AUTH LOGIN\r\n(?:250-8BITMIME\r\n)?250-SIZE\r\n250 DSN\r\n
      product: Novell NetWare GroupWise Internet Agent smtpd
      hostname: $1
      os: NetWare
      cpes:
        - a:novell:groupwise
        - o:novell:netware
    - name: smtp
      pattern:
        regex: ^220 .* Ready\r\n250-.*\r\n250-AUTH LOGIN\r\n(?:250-8BITMIME\r\n)?250-SIZE\r\n250 DSN\r\n
      product: Novell NetWare GroupWise Internet Agent smtpd
      os: NetWare
      cpes:
        - a:novell:groupwise
        - o:novell:netware
    - name: smtp
      pattern:
        regex: ^220 \[[\w_.-]+\] ESMTP Ready\r\n501 HELO requires domain address\r\n
      product: Canon imageRUNNER C5185 smtpd
      device-type: printer
      cpes:
        - h:canon:imagerunner_c5185
    - name: smtp
      pattern:
        regex: ^220 .* SMTP ready at .*\r\n501 Command \"EHLO\" requires an argument\r\n
      product: Lotus Domino smtpd
      cpes:
        - a:ibm:lotus_domino
    - name: smtp
      pattern:
        regex: ^220 Hello\r\n501 Command \"EHLO\" requires an argument\r\n
      product: Lotus Domino smtpd
      cpes:
        - a:ibm:lotus_domino
    - name: smtp
      pattern:
        regex: ^220 ([\w_.-]+)\r\n250-[\w._-]+ Axigen ESMTP hello\r\n
      product: Axigen smtpd
      hostname: $1
      cpes:
        - a:gecad:axigen_mail_server
    - name: smtp
      pattern:
        regex: ^220 [^\r\n]*ESMTP[^\r\n]*\r\n501 ehlo requires domain/address - see RFC-2821 4\.1\.1\.1\r\n
      product: qpsmtpd
      cpes:
        - a:ask_bjorn_hansen:qpsmtpd
    - name: smtp
      pattern:
        regex: ^220 ([\w_.-]+) ESMTP Service ready\r\n250-[\w_.-]+ Missing required domain name in EHLO, defaulted to your IP address \[[\d.]+\]\r\n
      product: Critical Path smtpd
      hostname: $1
    - name: smtp
      pattern:
        regex: ^220 \r\n501 \r\n
      product: Konica Minolta bizhub 350 printer smtpd
      device-type: printer
      cpes:
        - h:konicaminolta:bizhub_350
    - name: smtp
      pattern:
        regex: ^220 ([\w_.-]+) ESMTP SonicWALL \(([\d.]+)\)\r\n
      product: SonicWALL Email Security smtpd
      version: $2
      hostname: $1
      device-type: security-misc
    - name: smtp
      pattern:
        regex: ^220 ([\w_.-]+) ready\r\n250-[\w_.-]+\r\n250 AUTH LOGIN PLAIN \r\n$
      product: Freemail smtpd
      hostname: $1
    - name: smtp
      pattern:
        regex: ^554 SMTP synchronization error\r\n
      product: Exim smtpd
      cpes:
        - a:exim:exim
    - name: smtp
      pattern:
        regex: '^220 ([\w._-]+)  ESMTP\r\n501 Syntax: EHLO hostname\r\n'
      product: Postfix smtpd
      hostname: $1
      cpes:
        - a:postfix:postfix
    - name: smtp
      pattern:
        regex: '^220 ESMTP Postfix\r\n501 Syntax: EHLO hostname\r\n'
      product: Postfix smtpd
      cpes:
        - a:postfix:postfix
    - name: smtp
      pattern:
        regex: '^220-\*{89}\r\n220 \*{32}\r\n250-Welcome [\w._-]+, nice to meet you\.\.\.\r\n250-AUTH=(?:\w+ ?)+\r\n250-AUTH(?: \w+)+\r\n250-SIZE \d+\r\n250-DSN\r\n250-ETRN\r\n250 XXXA\r\n'
      product: ArGoSoft smtpd
      os: Windows
      cpes:
        - o:microsoft:windows
    - name: smtp
      pattern:
        regex: ^220 ESMTP Ready\r\n250-([\w._-]+) Hello \[[\d.]+\]\r\n250-SIZE\r\n250-PIPELINING\r\n250-DSN\r\n250-ENHANCEDSTATUSCODES\r\n250-STARTTLS\r\n250-X-ANONYMOUSTLS\r\n250-AUTH NTLM\r\n250-X-EXPS GSSAPI NTLM\r\n250-8BITMIME\r\n250-BINARYMIME\r\n250-CHUNKING\r\n250-XEXCH50\r\n250 XRDST\r\n
      product: Microsoft Outlook Web Access smtpd
      hostname: $1
    - name: smtp
      pattern:
        regex: ^220 ([\w._-]+) ESMTP\r\n250-\1\r\n250-STARTTLS\r\n250-SIZE 50000000\r\n250-PIPELINING\r\n250 8BITMIME\r\n
      product: qmail smtpd
      hostname: $1
      cpes:
        - a:djb:qmail
    - name: smtp
      pattern:
        regex: ^220  ESMTP\r\n501 5\.0\.0 EHLO requires domain address\r\n
      product: Sendmail
      cpes:
        - a:sendmail:sendmail
    - name: smtp
      pattern:
        regex: ^552 Invalid domain name in HELO command \(DLH use case\)\.\r\n
      product: Lotus Notes smtpd
      cpes:
        - a:ibm:lotus_domino
    - name: smtp
      pattern:
        regex: ^220 ([\w.-]+) ESMTP \w\w\w, \d\d \w\w\w \d\d\d\d [\d:]{8} ([-+]?\d\d\d\d)\r\n550 Invalid or missing command argument\(s\)\r\n
      product: MDaemon smtpd
      info: 'timezone: $2'
      hostname: $1
      cpes:
        - a:alt-n:mdaemon
    - name: smtp
      pattern:
        regex: ^220 ([\w.-]+) Ready\r\n250-Requested mail action okay, completed\.\r\n250 STARTTLS\r\n
      product: McAfee Email Gateway
      hostname: $1
      cpes:
        - a:mcafee:email_gateway
    - name: smtp
      pattern:
        regex: ^220 \S*[^\w.-]\S* ESMTP CommuniGate Pro [^\d].*\r\n250-([\w.-]+) domain name should be qualified \r\n
      product: CommuniGate Pro SMTP
      hostname: $1
      cpes:
        - a:stalker:communigate_pro
    - name: smtp
      pattern:
        regex: ^220 (\w[\w.-]+) ESMTP\r\n501 Syntactically invalid EHLO argument\(s\)\r\n
      product: Exim smtpd
      hostname: $1
      cpes:
        - a:exim:exim
    - name: smtp
      pattern:
        regex: ^220 ESMTP (?:\(NO U[BC]E\))* ?server ready at \w\w\w, \d\d \w\w\w \d\d\d\d [\d:]{8} ([-+]?\d\d\d\d)\r\n501 Command "EHLO" requires an argument\r\n
      product: Lotus Notes smtpd
      info: 'timezone: $1'
      cpes:
        - a:ibm:lotus_notes
    - name: smtp
      pattern:
        regex: ^220 ([\w._-]+) Mail ESMTP ready\r\n250-\1 Axigen ESMTP hello\r\n
      product: Axigen smtpd
      hostname: $1
      cpes:
        - a:gecad:axigen_mail_server
    - name: smtp
      pattern:
        regex: ^220 ([\w._-]+) Mail ESMTP ready\r\n250-([\w._-]+) Axigen ESMTP hello\r\n
      product: Axigen smtpd
      info: 'alt hostname: $2'
      hostname: $1
      cpes:
        - a:gecad:axigen_mail_server
    - name: smtp
      pattern:
        regex: ^220 ([\w._-]+)[^\r\n]*\r\n250-[^ ]* \[[^]]+\], this server offers \d+ extensions\r\n250
      product: MailEnable smtpd
      hostname: $1
      os: Windows
      cpes:
        - a:mailenable:mailenable
        - o:microsoft:windows
    - name: smtp
      pattern:
        regex: ^220 $
      product: OpenBSD spamd
    - name: smtp-proxy
      pattern:
        regex: ^220 ([-\w_.]+) .*\r\n250-[-\w_.]+ supports the following ESMTP extensions:\r\n250-SIZE \d+\r\n250-DSN\r\n250-8bitmime\r\n250 OK\r\n
      product: Trend Micro IMSS smtp proxy
      hostname: $1
      os: Windows
      cpes:
        - o:microsoft:windows
    - name: smtp-proxy
      pattern:
        regex: ^220 ([\w._-]+) ESMTP [\w._-]+\r\n501 5\.5\.2 HELO requires domain address\r\n
      product: SonicWALL Email Security Appliance smtp proxy
      hostname: $1
      device-type: proxy server
    - name: smtp-proxy
      pattern:
        regex: ^220 Ready to receive mail -=- ESMTP\r\n250-Ready to receive mail -=-\r\n250-AUTH LOGIN PLAIN\r\n250-AUTH=LOGIN PLAIN\r\n250-PIPELINING\r\n250 8BITMIME\r\n
      product: PineApp Mail-SeCure smtp proxy
      cpes:
        - a:pineapp:mail-secure
    - name: smtp-proxy
      pattern:
        regex: ^220 MailStore SMTP Proxy Server\r\n250-([\w._-]+)\r\n250-STARTTLS\r\n250 MAILSTORE\r\n
      product: MailStore smtp proxy
      hostname: $1
    - name: smtp-proxy
      pattern:
        regex: ^220 OutgoingFilter SMTP\r\n502 OutgoingFilter Command not implemented\r\n
      product: Dr.Web SMTP-proxy
      cpes:
        - a:drweb:smtp-proxy
