name: LDAPBindReq
protocol: tcp
rarity: 6
payload: \x30\x0c\x02\x01\x01\x60\x07\x02\x01\x02\x04\0\x80\0
ports: 256,257,389,390,1702,3268,3892,4035
ssl-ports: 636,637,3269,4035
services:
    - name: oo-defrag
      pattern:
        regex: ^h\0\0\0\x01\0\0\0\x03\0\0\0\x07\x08\0\0\x02\0\0\0\0d\0\0\0\0\xd9\$\x01\0\0\0\0\0\0T\0\0\0\0\0\0\xb7x\x01\0\0\0\0\0\xc4\x05\0\0\0\0\0\0\xc4\x05\0\0\0\0\0\0\xe2\x0b\0\0\0\0\0\0\xb7\xb5p@\^\xa7\x08\0\0\0\0\0
      product: O&O Defrag
      os: Windows
      cpes:
        - o:microsoft:windows
    - name: drobo-dsvc
      pattern:
        regex: ^(?:DRIDDSVC\x07\x01.\0\0\0..[^\0]*\0)?DRIDDSVC\x07\x01.\0\0\0..<ESATMUpdate>\r\n\t<mESAUpdateSignature>ESAINFO</mESAUpdateSignature>\r\n\t<mESAUpdateVersion>\d+</mESAUpdateVersion>\r\n\t<mESAUpdateSize>\d+</mESAUpdateSize>\r\n\t<mESAID>\w+</mESAID>\r\n\t<mSerial>\w+</mSerial>\r\n\t<mName>Drobo(?:-FS)?</mName>\r\n\t<mVersion>([][\w._ ]+)</mVersion>\r\n\t<mReleaseDate>([^<]+)</mReleaseDate>\r\n
        options: s
      product: Drobo-FS DDSVC
      version: $1 ($2)
    - name: fw1-secureremote
      pattern:
        regex: ^[AQ]\0\0\0\0\0\0[^\0]
      product: Check Point Firewall-1 SecureRemote
      device-type: firewall
      cpes:
        - a:checkpoint:firewall-1
    - name: fw1-log
      pattern:
        regex: ^\0\0\0\t51000000\0\0\0\0[^\0]
      product: Check Point Firewall-1 logging service
      device-type: firewall
      cpes:
        - a:checkpoint:firewall-1
    - name: ldap
      pattern:
        regex: ^0%\x02\x01\x01a \n\x010\x04\0\x04\x19anonymous bind disallowed$
      product: OpenLDAP
      info: access denied
      cpes:
        - a:openldap:openldap
    - name: ldap
      pattern:
        regex: ^02\x02\x01\x01a-\n\x01\x02\x04\0\x04&requested protocol version not allowed$
      product: OpenLDAP
      version: 2.1.X
      cpes:
        - a:openldap:openldap:2.1
    - name: ldap
      pattern:
        regex: ^0E\x02\x01\x01a@\n\x01\x02\x04\0\x049historical protocol version requested, use LDAPv3 instead
      product: OpenLDAP
      version: 2.2.X - 2.3.X
      cpes:
        - a:openldap:openldap
    - name: ldap
      pattern:
        regex: ^0\x84\0\0\0I\x02\x01\x01a\x84\0\0\0@\n\x01\x02\x04\0\x049historical protocol version requested, use LDAPv3 instead$
      product: OpenLDAP
      version: 2.4.X
      cpes:
        - a:openldap:openldap:2.4
    - name: ldap
      pattern:
        regex: ^0\x1a\x02\x01\x01a\x15\n\x01\0\x04\0\x04\x0eanonymous bind
      product: Nortel CallPilot LDAP
    - name: ldap
      pattern:
        regex: ^0\x0c\x02\x01\x01a\x07\n\x01\0\x04\0\x04\0
      info: Anonymous bind OK
    - name: ldap
      pattern:
        regex: ^0\x84\0\0\0\x10\x02\x01\x01a\x84\0\0\0\x07\n\x01\0\x04\0\x04\0$
    - name: ldap
      pattern:
        regex: '^0\x17\x02\x01\x01a\x12\n\x01\0\x04\0\x04\x0bPGPError #0$'
      product: PGP Corp. PGP Keyserver
      cpes:
        - a:pgp:keyserver
    - name: ldap
      pattern:
        regex: ^0\x0e\x02\x01\x01a\t\n\x01\0\x04\0\x04\0\x87\0$
      product: OctetString VDE directory service
    - name: ldap
      pattern:
        regex: ^0\.\x02\x01\x01a\)\n\x010\x04\0\x04\"Failed, anonymous bind not allowed$
      product: Lotus Domino 6.x LDAP
      info: access denied
      cpes:
        - a:ibm:lotus_domino
    - name: ldap
      pattern:
        regex: ^0\x0c\x02\x01\x01a\x07\n\x011\x04\0\x04\0$
      product: Cisco LDAP server
    - name: ldap
      pattern:
        regex: ^0.\x02.*TLS confidentiality required
        options: s
      info: TLS required
    - name: ldap
      pattern:
        regex: ^0&\x02\x01\x01a!\n\x01\x02\x04\0\x04\x1aOnly LDAP v3 is supported\.$
      product: ApacheDS LDAP
      info: LDAPv3
    - name: ldap
      pattern:
        regex: ^0\x1a\x02\x01\x01a\x15\n\x01\0\x04\0\x04\x0eBind succeeded$
      product: Siemens DirX
    - name: ldap
      pattern:
        regex: ^0 \x02\x01\x01a\x1b\n\x015\x04\0\x04\x14Minimum SSF not met\.
      product: Red Hat directory server LDAP
      info: Minimum SSF not met
      os: Linux
      cpes:
        - a:redhat:ns-slapd
        - o:redhat:directory_server
    - name: ldap
      pattern:
        regex: ^0\x81\xa0\x02\x01\x01a\x81\x9a\n\x011\x04\0\x04\x81\x92The server has been configured to only allow bind operations that result in authenticated connections\.  Anonymous bind operations are not allowed\.
      product: UnboundID LDAP SDK
      info: access denied
      cpes:
        - a:unboundid:ldap-sdk
    - name: rse
      pattern:
        regex: ^\xa2\x85\x99\xa5\x85\x99@
      product: IBM Explorer for zOS (FMID HALG300)
      os: z/OS
      cpes:
        - a:ibm:zos_explorer
        - o:ibm:z%2fos
fallback-services:
    - name: ldap
      pattern:
        regex: ^0..?\x02\x01\x01a..?\n\x01.\x04\0\x04
        options: s
