name: X11Probe
protocol: tcp
rarity: 4
payload: \x6C\0\x0B\0\0\0\0\0\0\0\0\0
ports: 80,443,497,1550,2002,5302,6000,6001,6002,6003,6004,6005,6006,6007,6008,6009,6010,6011,6012,6013,6014,6015,6016,6017,6018,6019,6020,7000,7100,7101,7777,8000
services:
    - name: acti-control
      pattern:
        regex: ^\x01\0\0\0\x01\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0$
      product: ACTi E32 camera control server port
      device-type: webcam
      cpes:
        - h:acti:e32
    - name: apcupsd
      pattern:
        regex: ^\0\0\x02\0\0\0\0\0\0\0\0\0\x06\0\0\0\0@\x0c\0\x9c\x18\0\0X Consortium\x01\n\x01\0\x05\0\0\0f\x84\x017\0\0\0\0\0\0\0\0$
      product: apcupsd
    - name: fastcgi
      pattern:
        regex: ^\x01\x0b\0\0\0\x08\0\0\0\0\0\0\0...
        options: s
      product: HHVM FastCGI
      cpes:
        - a:hiphop_virtual_machine_for_php_project:hiphop_virtual_machine_for_php
    - name: font-service
      pattern:
        regex: ^\0\0\x02\0\0\0\0\0\0\0\0\0\x06\0\0\0\0@\x0c\0p\x17\0\0X Consortium\x01\n\x01\0\x05\0\0\0....\0\0..\0\0\0\0$
        options: s
      product: Sun Solaris fs.auto
      os: Solaris
      cpes:
        - o:sun:sunos
    - name: font-service
      pattern:
        regex: ^\0\0\x02\0\0\0\0\0\0\0\0\0\x06\0\0\0\0@\x0c\0\xd4\x17\0\0X Consortium\x01\n\x01\0\x05\0\0\0....\0\0..\0\0\0\0$
        options: s
      product: HP-UX X Font Server
      os: HP-UX
      cpes:
        - o:hp:hp-ux
    - name: font-service
      pattern:
        regex: ^\0\0\x02\0\0\0\0\0\0\0\0\0\x0e\0\0\0\0 \*\0.\x19\0\0The XFree86 Project[-.\w() ]+..\x01\n\x01\0\x05\0\0\0....\0\0..\0\0\0
        options: s
      product: XFree86 X Font Server
      os: Unix
      cpes:
        - a:xfree86:xfree86
    - name: font-service
      pattern:
        regex: ^\0\0\x02\0\0\0\0\0\0\0\0\0\x07\0\0\0\0 \x10\0....X\.Org Foundation\x01\n
        options: s
      product: X.Org X Font Server
      os: Unix
      cpes:
        - a:x:x.org_x11
    - name: font-service
      pattern:
        regex: ^\0\0\x02\0\0\0\0\0\0\0\0\0\x07\0\0\0\0.......The X\.Org Group
        options: s
      product: X.Org X Font Server
      os: Unix
      cpes:
        - a:x:x.org_x11
    - name: font-service
      pattern:
        regex: ^\0\0\x02\0\0\0\0\0\0\0\0\0\x04\0\0\0\0.......HD\0@
        options: s
      product: X Font Server for TrueType Fonts
      os: Unix
    - name: font-service
      pattern:
        regex: ^\0\0\x02\0\0\0\0\0\0\0\0\0\r\0\0\0\0.......International Business Machines Corp\.
        options: s
      product: IBM AIX X Font Server
      os: AIX
      cpes:
        - o:ibm:aix
    - name: http-proxy
      pattern:
        regex: '^HTTP/1\.0 400 Bad request\r\nCache-Control: no-cache\r\nConnection: close\r\n\r\n<html><body><h1>400 Bad request</h1>\nYour browser sent an invalid request\.\n</body></html>\n$'
      product: HAProxy http proxy
      version: before 1.3.1
      device-type: load balancer
      cpes:
        - a:haproxy:haproxy
    - name: http-proxy
      pattern:
        regex: '^HTTP/1\.0 400 Bad request\r\nCache-Control: no-cache\r\nConnection: close\r\nContent-Type: text/html\r\n\r\n<html><body><h1>400 Bad request</h1>\nYour browser sent an invalid request\.\n</body></html>\n$'
      product: HAProxy http proxy
      version: 1.3.1 - 1.9.0
      device-type: load balancer
      cpes:
        - a:haproxy:haproxy
    - name: http-proxy
      pattern:
        regex: '^HTTP/1\.1 400 Bad request\r\nContent-length: 90\r\nCache-Control: no-cache\r\nConnection: close\r\nContent-Type: text/html\r\n\r\n<html><body><h1>400 Bad request</h1>\nYour browser sent an invalid request\.\n</body></html>\n$'
      product: HAProxy http proxy
      version: 2.0.0 or later
      device-type: load balancer
      cpes:
        - a:haproxy:haproxy
    - name: modbus
      pattern:
        regex: ^l\0\0\0\0\x03\0\x80\x01
      product: Modbus TCP
    - name: networkaudio
      pattern:
        regex: ^\0\x19\x02\0\x02\0\x07\0Protocol version mismatch\0
      product: Network Audio System
      cpes:
        - a:radscan:network_audio_system
    - name: retrospect
      pattern:
        regex: ^\0\xca\0\0\0\0\0\x04\0\0\0\0\0\0\x02\($
      product: Dantz Retrospect backup client
      cpes:
        - a:dantz:retrospect
    - name: rpcapd
      pattern:
        regex: '^\0\x01\0\x03\0\0\0/Incompatible version number: message discarded\.$'
      product: WinPcap remote packet capture daemon
      os: Windows
      cpes:
        - a:winpcap:winpcap
        - o:microsoft:windows
    - name: sphinx-search
      pattern:
        regex: ^\0\0\0\x01\0\x01\0\0\0\0\0\x1c\0\0\0\x18unknown command \(code=0\)
      product: Sphinx Search daemon
    - name: video
      pattern:
        regex: ^\0\xdc0@p\xdc0@3\.[0-9a-f]{8}\.[0-9A-F]......\0\x000\0\0\0..(?:\*\0/sda/1/\d+/\d+\.0123\.[0-9a-f]{8}\.[0-9A-F]......\0\x000\0\0\0..)+
        options: s
      product: ECV ECV-REC16SH webcam video stream
      device-type: webcam
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.....\0\0\0\0.*Sun Microsystems, Inc\.
        options: s
      product: XSun Solaris X11 server
      os: Solaris
      cpes:
        - o:sun:sunos
    - name: X11
      pattern:
        regex: ^\0\x2D\x0B\0\0\0\x0C\0
      info: access denied
    - name: X11
      pattern:
        regex: ^\0\x16\x0b\0\0\0\x06\0No protocol specified\x0a..$
        options: s
      info: access denied
      os: Unix
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0\0......\0\0.*The XFree86 Project, Inc
        options: s
      product: XFree86
      info: open
      os: Unix
      cpes:
        - a:xfree86:xfree86
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0\0......\0\0.*The X\.Org Foundation
        options: s
      product: X.Org
      info: open
      os: Unix
      cpes:
        - a:x:x.org_x11
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0\0.....\x02\0\0..\xff\xff\x1f\0\0\x01\0\0.*Gentoo Linux \(XFree86 (\d[^)]+)\)\0\0
        options: s
      product: XFree86
      version: $1
      info: Gentoo Linux
      os: Linux
      cpes:
        - a:xfree86:xfree86:$1
        - o:gentoo:linux
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0\0.....\x03\0\0..\xff\xff\x1f\0\0\x01\0\0.\0\xff\xff\x01\x07\0\0  \x08\xff....Gentoo Linux \(The X\.Org Foundation ([-\w_.]+), revision ([-\w_.]+)\)\0\0
        options: s
      product: X.Org
      version: $1 revision $2
      info: Gentoo Linux
      os: Linux
      cpes:
        - a:x:x.org_x11:$1
        - o:gentoo:linux
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0\0.....\x02\0\0.*Mandrake Linux \(XFree86 (\d[^\)]+)\)\0\0
        options: s
      product: XFree86
      version: $1
      info: Mandrake Linux
      os: Linux
      cpes:
        - a:xfree86:xfree86:$1
        - o:mandrakesoft:mandrake_linux
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0\0.....\x03\0\0.*Mandrakelinux \(X\.Org X11 ([\d.]+), patch level ([\w.]+)\)
        options: s
      product: X.Org
      version: $1 patch level $2
      info: Mandrake Linux
      os: Linux
      cpes:
        - a:x:x.org_x11:$1
        - o:mandrakesoft:mandrake_linux
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.*Conectiva Linux \(XFree86 ([\d.]+), patch level (\w+)\)
        options: s
      product: XFree86
      version: $1 patch level $2
      info: Connectiva Linux
      os: Linux
      cpes:
        - a:xfree86:xfree86:$1
        - o:linux:linux_kernel
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.....\0\0\0\0.*StarNet Communications Corp\.
        options: s
      product: StarNet X-Win32
      os: Windows
      cpes:
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\0J\x0b\0\0...This copy of X-Win32 will only accept connections from network ([\d.]+)\0\0
        options: s
      product: StarNet X-Win32
      info: Only accepting connections from net $1
      os: Windows
      cpes:
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0\0=\0\x01\0\0\0\0\0\xc0\x06\xff\xff\?.*\0DECWINDOWS Digital Equipment Corporation Digital UNIX V(\d[-.\w]+)\0\0\x01\x01
        options: s
      product: Digital UNIX X-Window
      version: $1
      info: Version is X Server and not of Digital UNIX
      os: Digital UNIX
      cpes:
        - o:dec:digital_unix
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0\0%\0\x04\r\0\0\0\0..\xff\xff\?\0\0\x01\0\0\x1b\0\xff\xff\x01\x02\0\0  \x08\xff....AT&T Laboratories Cambridge\0
        options: s
      product: Xvnc
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0......\0\0\0..\xff\xff\?\0.*AT&T Laboratories Cambridge
        options: s
      product: Xvnc
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0\0.\0..\0\0\0\0..\xff\xff\x1f\0\x01\0\0\0.\0\xff\xff.\x04\0\0\x08 \x08\xfe...\0Hummingbird Ltd\.\x01\x01 \0
        options: s
      product: Hummingbird Exceed X server
      version: 11.X
      os: Windows
      cpes:
        - a:hummingbird:exceed:11
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0\0.\0..\0\0\0\0..\xff\xff\?\0\x01\0\0\0.\0\xff\xff.\x04\x01\x01\x08 \x08\xfe...\0Hummingbird Ltd\.\x01\x01 \0
        options: s
      product: Hummingbird Exceed X server
      version: 8.X, 9.X, or 10.X
      os: Windows
      cpes:
        - a:hummingbird:exceed
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0\0.\0..\0\0\0\0..\xff\xff\?\0\x01\0\0\0.\0\xff\xff\x01\x04\x01\x01\x08 \x08\xfe...\0Hummingbird Communications Ltd\.\0\x01\x01 ...\0\0\x08\x08 ...\0\0\x0c\x0c ...\0\0\x18  ...\0\0.\0\0\0 \0\0\0\xff\xff\xff\0\0\0\0\0
        options: s
      product: Hummingbird Exceed X server
      version: 7.X
      os: Windows
      cpes:
        - a:hummingbird:exceed:7
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.....\0\0\0\0..\xff\xff\?\0\x01\0\0\0.\0\xff\xff\x01.\x01\x01\x08 \x08\xfe...\0Hummingbird Communications Ltd\..\x01\x01
        options: s
      product: Hummingbird Exceed X server
      version: 6.X
      os: Windows
      cpes:
        - a:hummingbird:exceed:6
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.....\0\0\0\0..\xff\xff.\0\x01\0\0..\0\xff\xff......\x08\xfe...\0Hummingbird Communications Ltd\.
        options: s
      product: Hummingbird Exceed X server
      os: Windows
      cpes:
        - a:hummingbird:exceed
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0......?\0\0\0...?\xff\xff.*Hummingbird Ltd\.
        options: s
      product: Hummingbird Exceed X server
      os: Windows
      cpes:
        - a:hummingbird:exceed
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.....\0\0\0\0..\xff\xff\?\0.\0\0..\0\xff\xff......\x08....\0DECWINDOWS compatibility\. Hummingbird
        options: s
      product: Hummingbird Exceed X server
      info: DECWINDOWS compatibility
      os: Windows
      cpes:
        - a:hummingbird:exceed
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.....\0\0\0\0..\xff\xff\?\0.\0\0..\0\xff\xff......\x08....\0DECWINDOWS DigitalEquipmentCorporation, eXcursion
        options: s
      product: DEC eXcursion X server
      os: Windows
      cpes:
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0......\0\0\0..\xff\xff\?\0.\0\0..\0\xff\xff.*Hewlett-Packard Company\0
        options: s
      product: Hewlett-Packard X server
      os: HP-UX
      cpes:
        - o:hp:hp-ux
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0......\0\0\0..\xff\xff\?\0.\0\0..\0\xff\xff.*Santa Cruz Operation Inc\.\0
        options: s
      product: SCO X server
      os: SCO UNIX
      cpes:
        - o:sco:sco_unix
    - name: X11
      pattern:
        regex: ^\0\0\0\x01\0\0\0\x0c\0\0\0\0$
      product: HP MC/ServiceGuard
      cpes:
        - a:hp:serviceguard
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0......\0\0\0..\xff\xff\?\0.*Labtam Europe Ltd\.\0\0\x01\x01
        options: s
      product: Labtam X-WinPro
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.....\0\0\0\0.*NetSarang Computer, Inc\.
        options: s
      product: NetSarang XManager
      os: Windows
      cpes:
        - a:netsarang:xmanager
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.....\0\0\0\0.*WRQ, Inc\.
        options: s
      product: ReflectionX
      os: Windows
      cpes:
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.....\0\0\0\0.*RealVNC Ltd
        options: s
      product: RealVNC
      cpes:
        - a:realvnc:realvnc
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.....\0\0\0\0.*Pexus Systems, Inc
        options: s
      product: Pexus X Server
      os: Windows
      cpes:
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.....\0\0\0\0.*HDS Network Systems, Inc\. \(([^)]+)\)
        options: s
      product: HDS X Server
      version: $1
      os: NetOS
      device-type: terminal server
      cpes:
        - o:hds:netos
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.*The Cygwin/X Project
        options: s
      product: Cygwin X Server Project
      os: Windows
      cpes:
        - a:redhat:cygwin
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.....\0\0\0\0.*Labtam Europe Ltd\.
        options: s
      product: Labtam X-WinPro
      os: Windows
      cpes:
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.....\0\0\0\0.*ASTEC, Inc\.
        options: s
      product: ASTEC-X
      os: Windows
      cpes:
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.....\0\0\0\0.*(?:LabF\.com|LabF)
        options: s
      product: LabF WinaXe
      os: Windows
      cpes:
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.....\0\0\0\0.*MicroImages, Inc\.\0
        options: s
      product: MicroImages MiX
      os: Windows
      cpes:
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.....\0\0\0\0.*Attachmate Corporation\0
        options: s
      product: Attachmate Kea! X server
      os: Windows
      cpes:
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.....\0\0\0\0.*WebTerm X ([\d.]+) by Powerlan USA\0
        options: s
      product: Powerlan WebTerm X server
      version: $1
      os: Windows
      cpes:
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.....\0\0\0\0.*Silicon Graphics
        options: s
      product: SGI IRIX X server
      os: IRIX
      cpes:
        - o:sgi:irix
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.......\0\0..\xff\xff.\0\0\x01\0\0.\0\xff\xff......\x08\xff....Colin Harrison\0
        options: s
      product: Xming X server
      os: Windows
      cpes:
        - a:straightrunning:xming
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.......\0\0..\xff\xff.\0\0\x01\0\0.\0\xff\xff......\x08\xff....The Xming Project\0
      product: Xming X server
      os: Windows
      cpes:
        - a:straightrunning:xming
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.....\0\0\0\0.*Open source\0
        options: s
      product: Android X Server
      os: Android
      device-type: phone
      cpes:
        - o:google:android
        - o:linux:linux_kernel
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0.....\0\0\0\0.*The X\.Org Group\0
        options: s
      product: Xvnc X11/VNC proxy
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0......\0\0\0.*Moba/X\0
        options: s
      product: MobaXterm
      os: Windows
      cpes:
        - a:mobatek:mobaxterm
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0......\0\0\0.*HC-Consult\0
        options: s
      product: VcXsrv X server
      os: Windows
      cpes:
        - a:hc-consult:vcxsrv
        - o:microsoft:windows
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0\0\x4C\0\xA0\xE0\x63\x02\0\0
      info: open
    - name: xfs
      pattern:
        regex: ^\0\0\x02\0\0\0\x01\0\x04\0\0\0\0\r([\w._-]+):\d+\0\x07\0\0\0\0 \x10\0,\x1a\0\0X\.Org Foundation\x01\n\x01\0\x05\0\0\0\xe6\xbf\xc0\xb5\0\0\0\0\0\0\0\0$
      product: X.Org xfs font server
      hostname: $1
      cpes:
        - a:x:x.org_x11
    - name: giop
      pattern:
        regex: ^GIOP\x01\0\x01\x06\0\0\0\0$
      product: omniORB omniNames
      info: Corba naming service
    - name: domain
      pattern:
        regex: ^\x80\xf0\x80\x12\0\x01\0\0\0\0\0\0\x20CKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\0\0!\0\x01
      product: Microsoft DNS
      os: Windows
      cpes:
        - a:microsoft:dns
        - o:microsoft:windows
    - name: gadu
      pattern:
        regex: ^UDAG$
      product: Kadu polish IM client
      cpes:
        - a:kadu:kadu
fallback-services:
    - name: X11
      pattern:
        regex: ^\x01\0\x0b\0\0......\0\0\0.
        options: s
