name: gkrellm
protocol: tcp
rarity: 9
payload: gkrellm 0.0.0
ports: "19150"
services:
    - name: gkrellm
      pattern:
        regex: ^<gkrellmd_setup>\n<version>\ngkrellmd ([\w._-]+)\n
      product: GKrellM System Monitor
      version: $1
