name: Quake1_server_info
protocol: udp
rarity: 9
payload: \x80\x00\x00\x0c\x02\x51\x55\x41\x4b\x45\x00\x03
ports: 26000,26001,26002,26003,26004
services:
    - name: quake
      pattern:
        regex: ^\x80\x00..\x83([^\x00]*)\x00([^\x00]*)\x00
      product: Quake 1 server
      info: 'address: $1, name: $2'
