name: DistCCD
protocol: tcp
rarity: 8
payload: DIST00000001ARGC00000005ARGV00000002ccARGV00000002-cARGV00000006nmap.cARGV00000002-oARGV00000006nmap.oDOTI00000000
ports: "3632"
services:
    - name: distccd
      pattern:
        regex: '^DONE00000001STAT00000000SERR00000000SOUT00000000DOTO.*?GCC: ([^\0]+)'
      product: distccd
      version: v1
      info: $1
    - name: distccd
      pattern:
        regex: '^DONE00000001STAT00000100SERR000000\w+/tmp/distccd_.*:\d+: internal compiler error: Segmentation fault'
      product: distccd
      info: broken
    - name: distccd
      pattern:
        regex: ^DONE00000001.*?DOTO00
      product: distccd
      version: v1
      info: unknown compiler
    - name: distccd
      pattern:
        regex: '^DONE00000001.*ccache: failed to create /usr/share/distcc/\.ccache \(Permission denied\)\n'
      product: distccd
      info: broken
    - name: distccd
      pattern:
        regex: ^DONE00000001.*CRITICAL! distcc seems to have invoked itself recursively!\n
        options: s
      product: distccd
      info: broken
    - name: distccd
      pattern:
        regex: '^[\w._-]+DONE[\w._-]+ .*ERROR: attempt to use unknown compiler aborted: ([\w._-]+)\n'
        options: s
      product: distccd
      info: 'broken: compiler $1 doesn''t exist'
