name: BackOrifice
protocol: udp
rarity: 9
payload: \xCE\x63\xD1\xD2\x16\xE7\x13\xCF\x38\xA5\xA5\x86\xB2\x75\x4B\x99\xAA\x32\x58
ports: "31337"
services:
    - name: BackOrifice
      pattern:
        regex: ^\xCE\x63\xD1\xD2\x16\xE7\x13\xCF........\x01\x12\x78\xC4\xE3\xD6\xA6\x65\x51\x75\x51\xEB\x2A\x3F
        options: s
      product: BackOrifice trojan
      version: "1.20"
      info: no password
      os: Windows
      cpes:
        - o:microsoft:windows
