name: afp
protocol: tcp
rarity: 6
payload: \x00\x03\0\x01\0\0\0\0\0\0\0\x02\0\0\0\0\x0f\0
ports: "548"
services:
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x8f[\x59\x79].([^\0\x01]+)[\0\x01].*Netatalk([\w._-]+)\x06\x06AFP2\.2\x06AFPX03\x06AFP3\.1\x06AFP3\.2\x06AFP3\.3\x06AFP3\.4
        options: s
      product: Netatalk
      version: $2
      info: 'name: $1; protocol 3.4'
      os: Unix
      cpes:
        - a:netatalk:netatalk:$2
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x8f\x7b.([^\0\x01]+)[\0\x01].*Netatalk([\w._-]+)\x05\x06AFP2\.2\x06AFPX03\x06AFP3\.1\x06AFP3\.2\x06AFP3\.3
        options: s
      product: Netatalk
      version: $2
      info: 'name: $1; protocol 3.3'
      os: Unix
      cpes:
        - a:netatalk:netatalk:$2
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x8f\x59.([^\0\x01]+)[\0\x01].*Netatalk([\w._-]+)\x05\x06AFP2\.2\x06AFPX03\x06AFP3\.1\x06AFP3\.2\x06AFP3\.3
        options: s
      product: Netatalk
      version: $2
      info: 'name: $1; protocol 3.3'
      os: Unix
      cpes:
        - a:netatalk:netatalk:$2
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x8f\x5d.MyBookWorld[\0\x01].*Netatalk([\w._-]+)\x05\x06AFP2\.2\x06AFPX03\x06AFP3\.1\x06AFP3\.2\x06AFP3\.3
        options: s
      product: Netatalk
      version: $1
      info: 'Western Digital MyBook World NAS device; name: MyBookWorld; protocol 3.3'
      os: Unix
      cpes:
        - a:netatalk:netatalk:$1
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x8f\x7d.([^\0\x01]+)[\0\x01].*Netatalk([\w._-]+)\x05\x06AFP2\.2\x06AFPX03\x06AFP3\.1\x06AFP3\.2\x06AFP3\.3
        options: s
      product: Netatalk
      version: $2
      info: 'name: $1; protocol 3.3'
      os: Unix
      cpes:
        - a:netatalk:netatalk:$2
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x8f\x79.([^\0\x01]+)[\0\x01].*Netatalk ([\w._-]+)\x05\x06AFP2\.2\x06AFPX03\x06AFP3\.1\x06AFP3\.2\x06AFP3\.3
        options: s
      product: Netatalk
      version: $2
      info: 'name: $1; protocol 3.3'
      os: Unix
      cpes:
        - a:netatalk:netatalk:$2
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x8f\x79.([\w._-]+)[\0\x01].*Netatalk([\w._-]+)\x05\x06AFP2\.2\x06AFPX03\x06AFP3\.1\x06AFP3\.2\x06AFP3\.3
        options: s
      product: Netatalk
      version: $2
      info: 'name: $1; protocol 3.3'
      os: Unix
      cpes:
        - a:netatalk:netatalk:$2
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x8f\x7d.(FreeNAS)[\0\x01].*Netatalk ([\w._-]+)\x05\x06AFP2\.2\x06AFPX03\x06AFP3\.1\x06AFP3\.2\x06AFP3\.3
        options: s
      product: Netatalk
      version: $2
      info: 'FreeNAS; name: $1; protocol 3.3'
      os: FreeBSD
      cpes:
        - a:netatalk:netatalk:$2
        - o:freebsd:freebsd
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x8f\x5d.([\w._-]+)[\0\x01].*Netatalk[ \0]?([\w._-]+)\x05\x06AFP2\.2\x06AFPX03\x06AFP3\.1\x06AFP3\.2\x06AFP3\.3
        options: s
      product: Netatalk
      version: $2
      info: 'name: $1; protocol 3.3'
      os: Unix
      cpes:
        - a:netatalk:netatalk:$2
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x8f\x7d.([^\0\x01]+)[\0\x01].*Netatalk ([\w._-]+)\x05\x06AFP2\.2\x06AFPX03\x06AFP3\.1\x06AFP3\.2\x06AFP3\.3
        options: s
      product: Netatalk
      version: $2
      info: 'name: $1; protocol 3.3'
      os: Unix
      cpes:
        - a:netatalk:netatalk:$2
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x8f\x7d.([^\0\x01]+)[\0\x01].*Netatalk([\w._-]+)\x06\x06AFP2\.2\x06AFPX03\x06AFP3\.1\x06AFP3\.2\x06AFP3\.3\x06AFP3\.4
      product: Netatalk
      version: $2
      info: 'name: $1; protocol 3.4'
      os: Unix
      cpes:
        - a:netatalk:netatalk:$2
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x8f\x7d.(MyBookWorld)[\0\x01].*Netatalk ([\w._-]+)\x05\x06AFP2\.2\x06AFPX03\x06AFP3\.1\x06AFP3\.2\x06AFP3\.3
        options: s
      product: Netatalk
      version: $SUBST(2,"-",".")
      info: 'Western Digital MyBook World NAS device; name: $1; protocol 3.3'
      os: Unix
      cpes:
        - a:netatalk:netatalk:$SUBST(2,"-",".")
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x8f\x7d.([\w._-]+)[\0\x01].*Netatalk([\w._-]+)\x08\x0eAFPVersion 1\.1\x0eAFPVersion 2\.0\x0eAFPVersion 2\.1\x06AFP2\.2\x06AFPX03\x06AFP3\.1\x06AFP3\.2\x06AFP3\.3
        options: s
      product: Netatalk
      version: $SUBST(2,"-",".")
      info: 'QNAP NAS TS-219P+; name: $1; protocol 3.3'
      os: Linux
      cpes:
        - a:netatalk:netatalk:$SUBST(2,"-",".")
        - o:linux:linux_kernel:2.6
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x81\x7d\0\0.*Netatalk\x06\x0eAFPVersion 1\.1\x0eAFPVersion 2\.0\x0eAFPVersion 2\.1\x06AFP2\.2\x06AFPX03\x06AFP3\.1\x04\x04DHX2\tDHCAST128
        options: s
      product: Netatalk
      info: protocol 3.1
      os: Unix
      cpes:
        - a:netatalk:netatalk
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x83\x7f.([^\0\x01]+)[\0\x01].*Netatalk\x04\x06AFP2\.2\x06AFPX03\x06AFP3\.1\x06AFP3\.2
        options: s
      product: Netatalk
      version: "2"
      info: 'name: $1; protocol 3.2'
      os: Unix
      cpes:
        - a:netatalk:netatalk:2
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x83\x7d.([^\0\x01]+)[\0\x01].*\x08Netatalk\x04\x06AFP2\.2\x06AFPX03\x06AFP3\.1\x06AFP3\.2
        options: s
      product: Netatalk
      version: "2"
      info: 'name: $1; protocol 3.2'
      os: Unix
      cpes:
        - a:netatalk:netatalk:2
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x83\x7d.([^\0\x01]+)[\0\x01].*\x08Netatalk\x06\x0eAFPVersion 1\.1\x0eAFPVersion 2\.0\x0eAFPVersion 2\.1\x06AFP2\.2\x06AFPX03\x06AFP3\.1
        options: s
      product: Netatalk
      version: "2"
      info: 'name: $1; protocol 3.1'
      os: Unix
      cpes:
        - a:netatalk:netatalk:2
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x83\x7d.([^\0\x01]+)[\0\x01].*\x08Netatalk\x07\x0eAFPVersion 1\.1\x0eAFPVersion 2\.0\x0eAFPVersion 2\.1\x06AFP2\.2\x06AFPX03\x06AFP3\.1\x06AFP3\.2
      product: Netatalk
      version: "2"
      info: 'name: $1; protocol 3.2'
      os: Unix
      cpes:
        - a:netatalk:netatalk:2
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x83\x79.([^\0\x01]+)[\0\x01].*\x08Netatalk\x06\x0eAFPVersion 1\.1\x0eAFPVersion 2\.0\x0eAFPVersion 2\.1\x06AFP2\.2\x06AFPX03\x06AFP3\.1
        options: s
      product: Netatalk
      version: "2"
      info: 'name: $1; protocol 3.1'
      os: Unix
      cpes:
        - a:netatalk:netatalk:2
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x83\x79.([^\0\x01]+)[\0\x01].*\x08Netatalk\x04\x06AFP2\.2\x06AFPX03\x06AFP3\.1\x06AFP3\.2
        options: s
      product: Netatalk
      version: "2"
      info: 'name: $1; protocol 3.2'
      os: Unix
      cpes:
        - a:netatalk:netatalk:2
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x83\x59.([^\0\x01]+)[\0\x01].*\x08Netatalk\x06\x0eAFPVersion 1\.1\x0eAFPVersion 2\.0\x0eAFPVersion 2\.1\x06AFP2\.2\x06AFPX03\x06AFP3\.1
        options: s
      product: Netatalk
      version: "2"
      info: 'name: $1; protocol 3.1'
      os: Unix
      cpes:
        - a:netatalk:netatalk:2
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x80\x7d.([^\0\x01]+)[\0\x01].*\x04unix\x04\x0eAFPVersion 1\.1\x0eAFPVersion 2\.0\x0eAFPVersion 2\.1\x06AFP2\.2
        options: s
      product: Netatalk
      version: "1.6"
      info: 'name: $1; protocol 2.2'
      os: Unix
      cpes:
        - a:netatalk:netatalk:1.6
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x8f\x79.([^\0\x01]+)[\0\x01].*Netatal(\d[\w.]+)
        options: s
      product: Netatalk
      version: $2
      info: 'name: $1'
      os: Unix
      cpes:
        - a:netatalk:netatalk:$2
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\0\xbf.([^\0]+)\0.*\x16Novell NetWare ([0-9.]+)\x06\x0eAFPVersion 1\.1\x0eAFPVersion 2\.0\x0eAFPVersion 2\.1\x06AFP2\.2\x06AFPX03\x06AFP3\.1\x02\x10[^\x16]+\x16
        options: s
      product: Novell NetWare AFP
      version: $2
      info: 'name: $1; protocol 3.1'
      os: NetWare
      cpes:
        - o:novell:netware
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\0\xb7.([^\0]+)\0.*\x1fNovell\x20Open\x20Enterprise\x20Server\x202
        options: s
      product: Novell Open Enterprise Server
      version: "2"
      info: 'name: $1'
      os: Linux
      cpes:
        - a:novell:open_enterprise_server:2
        - o:linux:linux_kernel
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x80\x7f.([^\0\x01]+)[\0\x01].*\x0aWindows NT\x03\x0eAFPVersion 2\.0\x0eAFPVersion 2\.1\x06AFP2\.2\x03\x10ClearTxt Passwrd\x0eMicrosoft V1\.0\x05MS2\.0
        options: s
      info: 'name: $1; protocol 2.2; MS2.0'
      os: Windows
      cpes:
        - o:microsoft:windows
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0........\x80\x7f.([^\0\x01]+)[\0\x01].*\x0aWindows NT\x03\x0eAFPVersion 2\.0\x0eAFPVersion 2\.1\x06AFP2\.2\x03\x0eMicrosoft V1\.0\x05MS2\.0\x05MS3\.0
        options: s
      info: 'name: $1; protocol 2.2; MS3.0'
      os: Windows
      cpes:
        - o:microsoft:windows
    - name: afp
      pattern:
        regex: '^\x01\x03\0\x01\0\0\0\0................\x03\xff.([^\0\x01]+)[\0\x01].*Windows Version: ([\d.]+ \(2\) build \d+ (?:Service Pack \d+)?) (\d+)-bit \(ExtremeZ-IP ([\w._-]+)\).*afpserver/([\w._@-]+)\0'
        options: s
      product: ExtremeZ-IP AFP
      version: $4
      info: 'name: $1; afpserver: $5; $3-bit'
      os: Windows $2
      cpes:
        - o:microsoft:windows
    - name: afp
      pattern:
        regex: '^\x01\x03\0\x01\0\0\0\0................\x03\xff.([^\0\x01]+)[\0\x01].*Windows Version: ([\d.]+ \(2\) build \d+ (?:Service Pack \d+)?) (\d+)-bit \(ExtremeZ-IP ([\w._-]+)\).*'
        options: s
      product: ExtremeZ-IP AFP
      version: $4
      info: 'name: $1; $3-bit'
      os: Windows $2
      cpes:
        - o:microsoft:windows
    - name: lsf-mbd
      pattern:
        regex: ^\0\"\0\0\x17\0\0\0\0\0\0\0\0\0\0\0
      product: Platform Load Sharing Facility MBD
      cpes:
        - a:platform:load_sharing_facility
    - name: pigpio
      pattern:
        regex: ^\0\x03\0\x01\0\0\0\0\0\0\0\x02\xa8\xff\xff\xff
      product: pigpiod
      cpes:
        - a:pigpio:pigpiod
fallback-services:
    - name: afp
      pattern:
        regex: ^\x01\x03\0\x01\0\0\0\0....\0\0\0\0.*AFP
        options: s
