name: RPCCheck
protocol: udp
rarity: 1
payload: \x72\xFE\x1D\x13\0\0\0\0\0\0\0\x02\0\x01\x86\xA0\0\x01\x97\x7C\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0
ports: 17,88,111,407,500,517,518,1419,2427,4045,10000,10080,12203,27960,32750,32751,32752,32753,32754,32755,32756,32757,32758,32759,32760,32761,32762,32763,32764,32765,32766,32767,32768,32769,32770,32771,32772,32773,32774,32775,32776,32777,32778,32779,32780,32781,32782,32783,32784,32785,32786,32787,32788,32789,32790,32791,32792,32793,32794,32795,32796,32797,32798,32799,32800,32801,32802,32803,32804,32805,32806,32807,32808,32809,32810,38978
services:
    - name: amanda
      pattern:
        regex: ^Amanda ([\d.]+) NAK HANDLE  SEQ 0\nERROR expected \"Amanda\", got \"r\xfe\x1d\x13\"\n
      product: Amanda backup service
      version: $1
      os: Unix
    - name: bittorrent-udp-tracker
      pattern:
        regex: ^\0\0\0\x02....\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0$
        options: s
      product: BitTorrent UDP tracker
    - name: bittorrent-udp-tracker
      pattern:
        regex: ^\x03\0\0\0\0\x01\x86\xa0Connection ID missmatch\.\0
      product: opentracker UDP tracker
      cpes:
        - a:dirk_engling:opentracker
    - name: bittorrent-utp
      pattern:
        regex: ^r\xfe\x1d\x13\0\0\0\0\0\0\0\0\0\0\0\0\xff\0\x03....$
        options: s
      product: uTorrent uTP
      os: Windows
      cpes:
        - a:utorrent:utorrent
        - o:microsoft:windows
    - name: bittorrent-utp
      pattern:
        regex: ^r\xfe\x1d\x13........\x7f\xff\xff\xff\xff\x02\x02..\0\x01\0\x08\0\0\0\0\0\0\0\0$
        options: s
    - name: brio
      pattern:
        regex: ^\0\0\x01\(\x16\x85..$
        options: s
      product: Brio 8 business intelligence
    - name: dnastar
      pattern:
        regex: ^....\0{7}.,PSH,[\x21-\x7e]{55}\0{800}
        options: s
      product: Dnastar Lasergene
      cpes:
        - a:dnastar:lasergene
    - name: slp-srvreg
      pattern:
        regex: ^\x02\x05\0\0\x12\0\0\0\0\0\0\x02\0\x02en\0\x0e$
      product: IBM Director SLP Service Registration
      info: slp_srvreg.exe
      cpes:
        - a:ibm:director
    - name: radius
      pattern:
        regex: ^\x03\xfe\0\x14................$
        options: s
      product: Juniper Steel-Belted Radius radiusd
    - name: rpcbind
      pattern:
        regex: ^\x72\xFE\x1D\x13\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01
    - name: rpcbind
      pattern:
        regex: ^\x72\xFE\x1D\x13\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x02
    - name: kerberos-sec
      pattern:
        regex: '^\x04\n\0\0\0\0\0\0\0\0\0\0\x04code = 4: packet version number unknown\0'
      product: OpenAFS
      cpes:
        - a:openafs:openafs
    - name: talk
      pattern:
        regex: ^\x01\xfe\x05\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0
      product: Talk server
    - name: chargen
      pattern:
        regex: NOPQRSTUVWXYZ\[\\\]\^_`abcdefghijklm
    - name: chargen
      pattern:
        regex: ^ !\"#\$%&'\(\)\*\+
      product: SunOS chargen
      os: SunOS
      cpes:
        - o:sun:sunos
    - name: isakmp
      pattern:
        regex: ^r\xfe\x1d\x13\0\0\0\0\0\0\0\x02\0\x01\x86\xa0\x0b\x10\x05\0\0\0\0\0\0\0\0
      product: Openswan ISAKMP
      cpes:
        - a:openswan:openswan
    - name: isakmp
      pattern:
        regex: ^r\xfe\x1d\x13\0\0\0\0\0\0\0\x02\0\x01\x86\xa0\) % \0\0\0\0\0\0\0\$\0\0\0\x08\0\0\0\x05
      product: StrongSwan ISAKMP
      cpes:
        - a:strongswan:strongswan
    - name: jetadmin
      pattern:
        regex: ^2;http://[\d.]+:\d+/;[\d.]+;\d+:\d+;\w+,[\d.]+,PLUGIN_LOADED
      product: HP Jetadmin
    - name: lantronix-config
      pattern:
        regex: ^\xff$
      product: Lantronix DSTni networking chip configuration
    - name: mp-automation
      pattern:
        regex: ^r\xfe\x1d\x13 ok
      product: Realtek MP Automation daemon
      device-type: WAP
    - name: nameserver
      pattern:
        regex: ^help\r\n\r\n\xff\xbf\xf8\xb0\xff7\0\x18\0\0\0\x01\0\0\0\0
      product: Solaris Internet Name Server
      os: Solaris
      cpes:
        - o:sun:sunos
    - name: ppp
      pattern:
        regex: ^\x7e\xff\x7d\x23\xc0!}!#} }8}\"}&} } } } }#}\$\xc2'}%}&Q\x93\xee,}'}\"}\(}\"}\(D~
      product: pppd
      version: 2.4.5
    - name: qotd
      pattern:
        regex: ^"(?:My spelling is Wobbly\.|Man can climb to the highest summits,|In Heaven an angel is nobody in particular\.|Assassination is the extreme form of censorship\.|When a stupid man is doing|We have no more right to consume happiness without|We want a few mad people now.|The secret of being miserable is to have leisure to|Here's the rule for bargains:|Oh the nerves, the nerves; the mysteries of this machine called man|A wonderful fact to reflect upon,|It was as true as taxes is\.)
      product: Windows qotd
      info: English
      os: Windows
      cpes:
        - a:microsoft:qotd::::en
        - o:microsoft:windows
    - name: qotd
      pattern:
        regex: ^"(?:Mi ortograf\xeda tiembla\. Es bueno revisarla,|un hombre puede escalar a las m\xe1s altas cumbre|Algo maravilloso a poner de manifiesto:|Cuando un necio hace algo de lo que se aveg\xfcenza,|En el cielo, un \xe1ngel no es nadie en concreto|Traigamos unos cuantos locos ahora\.|Era tan verdad como los impuestos\. Y no|Hay libros cortos que, para entenderlos como se merecen,|Quedarse en lo conocido por miedo a lo desconocido,|La prosperidad hace amistades, y la adversidad las|El uso principal de un PC es confirmar la ley de|Quedarse en lo conocido por miedo a lo desconocido,|Cuando las leyes son injustas, no obligan en el fuero|Magia equivale a cualquier avance en la ciencia\.|Vale mejor consumir vanidades de la vida,)
      product: Windows qotd
      info: Spanish
      os: Windows
      cpes:
        - a:microsoft:qotd::::es
        - o:microsoft:windows
    - name: qotd
      pattern:
        regex: ^.(?:Voce dal sen fuggita|Semel in anno licet insanire|Cosa bella e mortal passa e non dura|Quando uno stupido compie qualcosa di cui si vergogna,|Se tu pagare come dici tu,|Fatti non foste a viver come bruti,|Sperare senza far niente e` come)
      product: Windows qotd
      info: Italian
      os: Windows
      cpes:
        - a:microsoft:qotd::::it
        - o:microsoft:windows
    - name: qotd
      pattern:
        regex: ^"(?:Prazos longos sao f\xa0ceis de subscrever\.|Deus, para a felicidade do homem, inventou a f\x82 e o amor\.|Ao vencido, \xa2dio ou compaixao, ao vencedor, as batatas\.|Quem nao sabe que ao p\x82 de cada bandeira p\xa3blica,|Nao te irrites se te pagarem mal um benef\xa1cio; antes cair|A vida, como a antiga Tebas, tem cem portas\.)
      product: Windows qotd
      info: Portuguese
      cpes:
        - a:microsoft:qotd::::pt
    - name: qotd
      pattern:
        regex: ^(?:Wer wirklich Autorit\xe4t hat, wird sich nicht scheuen,|Moral ist immer die Zuflucht der Leute,|Beharrlichkeit wird zuweilen mit Eigensinn|Wer den Tag mit Lachen beginnt, hat ihn|Wenn uns keine Ausweg mehr bleibt,|Gesichter sind die Leseb\xfccher des Lebens|Grosse Ereignisse werfen mitunter ihre Schatten|Dichtung ist verpflichtet, sich nach den|Ohne Freihet geht das Leben|Liebe ist wie ein Verkehrsunfall\. Man wird angefahren)
      product: Windows qotd
      info: German
      cpes:
        - a:microsoft:qotd::::de
    - name: qotd
      pattern:
        regex: ^"(?:Clovek ma tri cesty, jak moudre jednat\. Nejprve premyslenim|Co je vubec hodno toho, aby to bylo vykonano,|Fantazie je dulezitejsi nez vedeni\.|Potize narustaji, cim vice se clovek blizi|Kdo nezna pristav, do ktereho se chce plavit,|Lidske mysleni ztraci smysl,|Nikdo nevi, co muze vykonat,|Nic neprekvapi lidi vice nez zdravy rozum|Zadny cil neni tak vysoky,)
      product: Windows qotd
      info: Czech
      os: Windows
      cpes:
        - a:microsoft:qotd::::cs
        - o:microsoft:windows
    - name: qotd
      pattern:
        regex: ^"(?:L'art de persuader consiste autant|Le peu que je sais, c'est \x85 mon ignorance|Certaines \x83mes vont \x85 l'absolu comme l'eau|Le m\x82rite a sa pudeur comme la chastet|Rien de plus futile, de plus faux, de plus|\xb7 vaincre sans p\x82ril, on triomphe|Le comble de l'orgueil, c'est de se)
      product: Windows qotd
      info: French
      os: Windows
      cpes:
        - a:microsoft:qotd::::fr
        - o:microsoft:windows
    - name: mohaa
      pattern:
        regex: \xff\xff\xff\xff\x01disconnect
      product: Medal Of Honor Allied Assault game server
    - name: mohaa-gamespy
      pattern:
        regex: ^\\final\\\\queryid\\\d+\.1
      product: Medal Of Honor Allied Assault gamespy query port
    - name: ericssontimestep
      pattern:
        regex: ^.{8}\0\0\0\0\0\0\0\0\x0b\x10\x05\0\0\0\0\0\0\0\0\(\0\0\0\x0c\0\0\0\0\x01\0\0\x1e$
        options: s
      product: Ericsson Timestep Permit VPN
    - name: rtp
      pattern:
        regex: ^501 0 Endpoint is not ready - Unrecognized command verb\n
    - name: sauerbraten
      pattern:
        regex: ^r\xfe\x1d\x13\0\0\0\0\0\0\0\x02\0\x01\x86\xa0\0\x01\x97\x7c\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x05\x80\x02\x01\0\0\x0c\0\0([\w._ -]+)\0$
      product: Sauerbraten game server
      info: 'server name: $1'
    - name: sentinel-lm
      pattern:
        regex: ^r\xfe\x1d\x13\0\0\0\0\0\0\0\x02,PSH,'A{\^QOHpe\]\)\]\\\^cRH>%gNQX$
      product: SafeNet Sentinel License Manager
    - name: ssdp
      pattern:
        regex: ^HTTP/1\.1 200 OK\r\nST:upnp:rootdevice\r\nUSN:uuid:11111111-0000-c0a8-0101-efefefef8035::upnp:rootdevice\r\nLocation:http://[\d.]+:\d+/DeviceDescription\.xml\r\nCache-Control:max-age=480\r\nServer:Allegro-Software-RomUpnp/([\w._-]+) UPnP/([\w._-]+) IGD/1\.00\r\nExt:\r\n\r\n
        options: s
      product: Allegro RomUPnP
      version: $1
      info: UPnP $2
    - name: timbuktu
      pattern:
        regex: ^\0#\xd1\x1f$
      product: Timbuktu remote desktop
    - name: utorrent-udp
      pattern:
        regex: ^\x72\xfe\x1d\x13\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03....$
        options: s
      product: uTorrent UDP listener
      os: Windows
      cpes:
        - a:utorrent:utorrent
        - o:microsoft:windows
    - name: webmin
      pattern:
        regex: ^0\.0\.0\.0:(\d+):0:?$
      info: http on TCP port $1
    - name: webmin
      pattern:
        regex: ^([^:]*):(\d+):0:?$
      info: http on TCP $1:$2
    - name: webmin
      pattern:
        regex: ^0\.0\.0\.0:(\d+):0:(.+)$
      info: http on TCP port $1 ($2)
    - name: webmin
      pattern:
        regex: ^([^:]*):(\d+):0:(.+)$
      info: http on $1:$2 ($3)
    - name: webmin
      pattern:
        regex: ^0\.0\.0\.0:(\d+):1:?$
      info: https on TCP port $1
    - name: webmin
      pattern:
        regex: ^([^:]*):(\d+):1:?$
      info: https on TCP $1:$2
    - name: webmin
      pattern:
        regex: ^0\.0\.0\.0:(\d+):1:(.+)$
      info: https on TCP port $1 ($2)
    - name: webmin
      pattern:
        regex: ^([^:]*):(\d+):1:(.+)$
      info: https on $1:$2 ($3)
    - name: apple-sasl
      pattern:
        regex: How was your weekend\?;[0-9A-F]*\0
      product: Mac OS X Server Password Server
      os: Mac OS X
      cpes:
        - o:apple:mac_os_x
    - name: nat-pmp
      pattern:
        regex: ^\0\xfe\0\x01\0\0..$
        options: s
      product: natpmp daemon
      device-type: router
    - name: nat-pmp
      pattern:
        regex: ^\0\0\0\x01...\0$
        options: s
      product: Apple Time Capsule
      device-type: router
    - name: xdmcp
      pattern:
        regex: ^\0\x01\0\x05..\0\0\0.(.+)\0.(.+)
        options: s
      product: XDMCP
      info: 'willing; status: $2'
      hostname: $1
      os: Unix
    - name: dtls
      pattern:
        regex: ^\x15\xfe[\xfd\xff]\0\0\0\0\0\0\0\0..\x02.\0\0\0\0\0
fallback-services:
    - name: quake3
      pattern:
        regex: ^\xff\xff\xff\xffdisconnect$
      product: Quake 3 game server
    - name: domain
      pattern:
        regex: ^r\xfe[\x98-\x9f][\x02\x12\x82\x92]\0\0\0\0\0\0\0\0
