name: Kerberos
protocol: tcp
rarity: 5
payload: \0\0\0\x71\x6a\x81\x6e\x30\x81\x6b\xa1\x03\x02\x01\x05\xa2\x03\x02\x01\x0a\xa4\x81\x5e\x30\x5c\xa0\x07\x03\x05\0\x50\x80\0\x10\xa2\x04\x1b\x02NM\xa3\x17\x30\x15\xa0\x03\x02\x01\0\xa1\x0e\x30\x0c\x1b\x06krbtgt\x1b\x02NM\xa5\x11\x18\x0f19700101000000Z\xa7\x06\x02\x04\x1f\x1e\xb9\xd9\xa8\x17\x30\x15\x02\x01\x12\x02\x01\x11\x02\x01\x10\x02\x01\x17\x02\x01\x01\x02\x01\x03\x02\x01\x02
ports: "88"
services:
    - name: kerberos-sec
      pattern:
        regex: ^\0\0\0[\x88-\x8a]~\x81[\x86-\x88]0\x81[\x83-\x85]\xa0\x03\x02\x01\x05\xa1\x03\x02\x01\x1e\xa2\x11\x18\x0f\d{14}Z\xa4\x11\x18\x0f(\d\d\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)Z\xa5[\x03-\x05]\x02(?:\x03...|\x02..|\x01.)\xa6\x03\x02\x01\x06\xa9\x04\x1b\x02NM\xaa\x170\x15\xa0\x03\x02\x01\0\xa1\x0e0\x0c\x1b\x06krbtgt\x1b\x02NM\xab\(\x1b&Client not found in Kerberos database\0$
        options: s
      product: MIT Kerberos
      version: "1.2"
      info: 'server time: $1-$2-$3 $4:$5:$6Z'
      cpes:
        - a:mit:kerberos:5-1.2
    - name: kerberos-sec
      pattern:
        regex: ^\0\0\0[\x6d-\x6f]~[\x6b-\x6d]0[\x69-\x6b]\xa0\x03\x02\x01\x05\xa1\x03\x02\x01\x1e\xa2\x11\x18\x0f\d{14}Z\xa4\x11\x18\x0f(\d\d\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)Z\xa5[\x03-\x05]\x02(?:\x03...|\x02..|\x01.)\xa6\x03\x02\x01\x06\xa9\x04\x1b\x02NM\xaa\x170\x15\xa0\x03\x02\x01\0\xa1\x0e0\x0c\x1b\x06krbtgt\x1b\x02NM\xab\x0e\x1b\x0cNULL_CLIENT\0$
        options: s
      product: MIT Kerberos
      version: 1.3 - 1.8
      info: 'server time: $1-$2-$3 $4:$5:$6Z'
      cpes:
        - a:mit:kerberos:5-1
    - name: kerberos-sec
      pattern:
        regex: ^\0\0\0[\x62-\x64]~[\x60-\x62]0[\x5e-\x60]\xa0\x03\x02\x01\x05\xa1\x03\x02\x01\x1e\xa4\x11\x18\x0f(\d\d\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)Z\xa5[\x03-\x05]\x02(?:\x03...|\x02..|\x01.)\xa6\x03\x02\x01<\xa9\x04\x1b\x02NM\xaa\x170\x15\xa0\x03\x02\x01\0\xa1\x0e0\x0c\x1b\x06krbtgt\x1b\x02NM\xab\x16\x1b\x14No client in request$
        options: s
      product: Heimdal Kerberos
      info: 'server time: $1-$2-$3 $4:$5:$6Z'
      cpes:
        - a:heimdal:kerberos
    - name: kerberos-sec
      pattern:
        regex: ^\0\0\0[\x4a-\x4c]~[\x48-\x4a]0[\x46-\x48]\xa0\x03\x02\x01\x05\xa1\x03\x02\x01\x1e\xa4\x11\x18\x0f(\d\d\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)Z\xa5[\x03-\x05]\x02(?:\x03...|\x02..|\x01.)\xa6\x03\x02\x01D\xa9\x04\x1b\x02NM\xaa\x170\x15\xa0\x03\x02\x01\0\xa1\x0e0\x0c\x1b\x06krbtgt\x1b\x02NM$
        options: s
      product: Microsoft Windows Kerberos
      info: 'server time: $1-$2-$3 $4:$5:$6Z'
      os: Windows
      cpes:
        - a:microsoft:kerberos
        - o:microsoft:windows
    - name: kerberos-sec
      pattern:
        regex: ^\0\0\0[\x79-\xf0]\0[\x79-\xf0]\0\x01\0\0~[\x71-\xe8]0[\x69-\x80]\xa0\x03\x02\x01\x05\xa1\x03\x02\x01\x1e\xa4\x11\x18\x0f(\d\d\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)Z\xa5[\x03-\x05]\x02(?:\x03...|\x02..|\x01.)\xa6\x03\x02\x01<\xa9.\x1b.([\w.-]+)\xaa\x1d0\x1b\xa0\x03\x02\x01\0\xa1\x140\x12\x1b\x06kadmin\x1b\x08changepw\xac#\x04!\0\x01Request length was inconsistent
        options: s
      product: MIT Kerberos
      info: 'OpenWRT; server time: $1-$2-$3 $4:$5:$6Z; realm: $7'
      cpes:
        - a:mit:kerberos
    - name: netradio
      pattern:
        regex: ^@(?:NETRADIO|MAIN|SYS):[A-Z0-9]+=
      product: Yamaha Net Radio
      device-type: media device
    - name: qemu-vlan
      pattern:
        regex: ^\0\0\0qj\x81n0\x81k\xa1\x03\x02\x01\x05\xa2\x03\x02\x01\n\xa4\x81\^0\\\xa0\x07\x03\x05\0P\x80\0\x10\xa2\x04\x1b\x02NM\xa3\x170\x15\xa0\x03\x02\x01\0\xa1\x0e0\x0c\x1b\x06krbtgt\x1b\x02NM\xa5\x11\x18\x0f19700101000000Z
      product: QEMU VLAN listener
      cpes:
        - a:qemu:qemu
    - name: sap-gui
      pattern:
        regex: ^\0\0\0\x0e\*\*DPTMMSG\*\*\0\0\xf8
      product: SAP Gui Dispatcher
      cpes:
        - a:sap:gui
fallback-services:
    - name: smpp
      pattern:
        regex: ^\0\0\0\x10\x80\0\0\0\0\0\0\x03....$
        options: s
    - name: postgresql
      pattern:
        regex: ^E\0\0\0.SFATAL\0(?:VFATAL\0)?C\w{5}\0M
      product: PostgreSQL DB
      cpes:
        - a:postgresql:postgresql
