name: mongodb
protocol: tcp
rarity: 8
payload: \x41\0\0\0\x3a\x30\0\0\xff\xff\xff\xff\xd4\x07\0\0\0\0\0\0test.$cmd\0\0\0\0\0\xff\xff\xff\xff\x1b\0\0\0\x01serverStatus\0\0\0\0\0\0\0\xf0\x3f\0
ports: 9001,27017,49153
services:
    - name: mongodb
      pattern:
        regex: ^.*version.....([\.\d]+)
        options: s
      product: MongoDB
      version: $1
      cpes:
        - a:mongodb:mongodb:$1
    - name: mongodb
      pattern:
        regex: ^\xcb\0\0\0....:0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\xa7\0\0\0\x01uptime\0\0\0\0\0\0 `@\x03globalLock\09\0\0\0\x01totalTime\0\0\0\0\x7c\xf0\x9a\x9eA\x01lockTime\0\0\0\0\0\0\xac\x9e@\x01ratio\0!\xc6\$G\xeb\x08\xf0>\0\x03mem\0<\0\0\0\x10resident\0\x03\0\0\0\x10virtual\0\xa2\0\0\0\x08supported\0\x01\x12mapped\0\0\0\0\0\0\0\0\0\0\x01ok\0\0\0\0\0\0\0\xf0\?\0$
        options: s
      product: MongoDB
      cpes:
        - a:mongodb:mongodb
    - name: mongodb
      pattern:
        regex: ^.\0\0\0....:0\0\0\x01\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\+\0\0\0\x02errmsg\0\x0e\0\0\0need to login\0\x01ok\0\0\0\0\0\0\0\0\0\0
        options: s
      product: MongoDB
      version: 2.3.1 or earlier
      info: need to login
      cpes:
        - a:mongodb:mongodb
    - name: mongodb
      pattern:
        regex: '^.\0\0\0....:0\0\0\x01\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0.\0\0\0\x01ok\0\0\0\0\0\0\0\0\0\x02errmsg\0.\0\0\0not authorized on (\S+) to execute command \{ serverStatus: 1\.0 \}\0\x10code\0\r\0\0\0'
        options: s
      product: MongoDB
      version: 2.3.2 - 4.1.0
      info: 'not authorized; database: $1'
      cpes:
        - a:mongodb:mongodb
    - name: mongodb
      pattern:
        regex: ^.\0\0\0....:0\0\0\x01\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0o\0\0\0\x01ok\0\0\0\0\0\0\0\0\0\x02errmsg\0-\0\0\0command serverStatus requires authentication\0\x10code\0\r\0\0\0\x02codeName\0\r\0\0\0Unauthorized\0\0
        options: s
      product: MongoDB
      version: 4.1.1 - 5.0
      cpes:
        - a:mongodb:mongodb
    - name: mongodb
      pattern:
        regex: ^..\0\0....:0\0\0\x01\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\xec\0\0\0\x11operationTime\0........\x01ok\0\0\0\0\0\0\0\0\0\x02errmsg\0-\0\0\0command serverStatus requires authentication\0\x10code\0\r\0\0\0\x02codeName\0\r\0\0\0Unauthorized\0\x03\$clusterTime\0X\0\0\0\x11clusterTime\0........\x03signature\x003\0\0\0\x05hash\0\x14\0\0\0\0....................\x12keyId\0........\0\0\0
        options: s
      product: MongoDB
      info: auth required
      cpes:
        - a:mongodb:mongodb
    - name: mongodb
      pattern:
        regex: '^..\0\0....:0\0\0\x01\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0.\0\0\0\x01ok\0\0\0\0\0\0\0\0\0\x02errmsg\0.\0\0\0Unsupported OP_QUERY command: serverStatus\0\x10code\0`\x01\0\0\x02codeName\0\x1a\0\0\0UnsupportedOpQueryCommand\0\0'
      product: MongoDB
      version: 5.1 - 6.0
      cpes:
        - a:mongodb:mongodb
    - name: mongodb
      pattern:
        regex: '^..\0\0....:0\0\0\x01\0\0\0.\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\xf0\0\0\0\x01ok\0\0\0\0\0\0\0\0\0\x02errmsg\0\xa1\0\0\0Unsupported OP_QUERY command: serverStatus\. The client driver may require an upgrade\. For more details see https://dochub\.mongodb\.org/core/legacy-opcode-removal\0\x10code\0`\x01\0\0\x02codeName\0\x1a\0\0\0UnsupportedOpQueryCommand\0\0'
      product: MongoDB
      version: 6.1 or later
      cpes:
        - a:mongodb:mongodb
