name: beast2
protocol: tcp
rarity: 9
payload: "666"
ports: 666,6666
services:
    - name: backdoor
      pattern:
        regex: ^666(\d+)\xff(\d+)\xff(\d+)\xff$
      product: Beast Trojan
      version: version 2
      info: '**BACKDOOR**; No password; New server port: $1; New client ports: $2, $3'
      os: Windows
      cpes:
        - o:microsoft:windows
