name: metasploit-xmlrpc
protocol: tcp
rarity: 9
payload: <?xml version="1.0" ?><methodCall><methodName>nmap.probe</methodName></methodCall>\n\0
ports: 9390,55553
ssl-ports: "55553"
services:
    - name: metasploit-xmlrpc
      pattern:
        regex: <\?xml\x20version=\"1\.0\"\x20\?><methodResponse><fault><value><struct><member><name>faultCode</name><value><i4>-99</i4></value></member><member><name>faultString</name><value><string>Method\x20nmap\.probe\x20missing\x20or\x20wrong\x20number\x20of\x20parameters!</string></value></member></struct></value></fault></methodResponse>\n\0
    - name: omp
      pattern:
        regex: ^<omp_response status=\"400\" status_text=\"First command must be AUTHENTICATE, COMMANDS or GET_VERSION\"/>
      product: OpenVAS Management Protocol
      cpes:
        - a:openvas:openvas_manager
