name: ASE
protocol: udp
rarity: 9
payload: s
ports: 1258,2126,3123,12444,13200,23196,26000,27138,27244,27777,28138
services:
    - name: allseeingeye
      pattern:
        regex: ^EYE1.(.*?)(\x02\d|\x03\d{2}|\x04\d{3}|\x05\d{4}|\x06\d{5})
        options: s
      product: All-Seeing Eye
      info: 'game: $1; port: $P(2)'
