name: metasploit-msgrpc
protocol: tcp
rarity: 9
payload: GET /api HTTP/1.0\r\n\r\n
ports: 50505,55552
ssl-ports: "3790"
services:
    - name: metasploit-msgrpc
      pattern:
        regex: '^HTTP/1\.1 200 OK\r\nContent-Type: binary/message-pack\r\nConnection: close\r\nServer: Rex\r\nContent-Length: 1084\r\n\r\n\x85\xa5error\xc3\xaberror_class\xadArgumentError\xacerror_string\xbdInvalid Request Verb: ''\"GET\"''\xaferror_backtrace\xdc\x00\x12\xda\x000lib/msf/core/rpc/v10/service\.rb:107:in `process''\xda\x006lib/msf/core/rpc/v10/service\.rb:88:in `on_request_uri''\xda\x006lib/msf/core/rpc/v10/service\.rb:70:in `block in start''\xda\x00/lib/rex/proto/http/handler/proc\.rb:37:in `call''\xda\x005lib/rex/proto/http/handler/proc\.rb:37:in `on_request''\xda\x00'
      product: Metasploit Remote API
      version: 4.4.0-dev
