name: FreelancerStatus
protocol: udp
rarity: 9
payload: \x00\x02\xf1\x26\x01\x26\xf0\x90\xa6\xf0\x26\x57\x4e\xac\xa0\xec\xf8\x68\xe4\x8d\x21
ports: "2302"
services:
    - name: freelancer
      pattern:
        regex: ^\x00\x03\xf1\x26.{88}(.*)\0\0(?:.*?:){5}(.*)\0\0$
        options: s
      product: Freelancer
      info: 'name: $P(1); description: $P(2)'
