name: giop
protocol: tcp
rarity: 7
payload: GIOP\x01\x00\x01\x00$\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x06\x00\x00\x00abcdef\x00\x00\x04\x00\x00\x00get\x00\x00\x00\x00\x00
ports: "2481"
ssl-ports: "2482"
services:
    - name: giop
      pattern:
        regex: ^GIOP\x01\0\x01\x01@\0\0\0\0\0\0\0\x01\0\0\0\x02\0\0\0'\0\0\0IDL:omg\.org/CORBA/OBJECT_NOT_EXIST:1\.0\0
      product: omg.org CORBA naming service
    - name: giop
      pattern:
        regex: ^GIOP\x01\0\0\x01\0\0\0@\0\0\0\0\0\0\0\x01\0\0\0\x02\0\0\0'IDL:omg\.org/CORBA/OBJECT_NOT_EXIST:1\.0\0\0OM\0\x02\0\0\0\x01
      product: omg.org CORBA naming service
    - name: giop
      pattern:
        regex: ^GIOP\x01\0\0\x01\0\0..\0\0\0.\0\0\0\x06.*https?://[\w._-]+:\d+/bea_wls_internal/classes/
        options: s
      product: WebLogic Server IIOP
      cpes:
        - a:oracle:weblogic_server
    - name: iscsi
      pattern:
        regex: ^#\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\0
      product: Synology DSM iSCSI
fallback-services:
    - name: giop
      pattern:
        regex: ^GIOP\x01\x00\x01\x01........\x01\x00\x00\x00
    - name: giop
      pattern:
        regex: ^GIOP.*IDL:omg\.org
        options: s
