name: TLS-PSK
protocol: tcp
rarity: 9
payload: \x16\x03\x00\x00u\x01\x00\x00q\x03\x03U8*bETXSJDSZNHMDFAONDKJXXZYZHWHR\x00\x000\x00\x8a\x00\x8b\x00\x8c\x00\x8d\x00\x8e\x00\x8f\x00\x90\x00\x91\x00\x92\x00\x93\x00\x94\x00\x95\x00\xa8\x00\xa9\x00\xaa\x00\xab\x00\xac\x00\xad\x00\xae\x00\xaf\x00\xb2\x00\xb3\x00\xb6\x00\xb7\x01\x00\x00\x18\x00\r\x00\x14\x00\x12\x00\x01\x00\x02\x00\x03\x01\x01\x01\x02\x01\x03\x02\x01\x02\x02\x02\x03
ports: "27036"
services:
    - name: ssl/steam
      pattern:
        regex: ^\x16\x03\x03\0.\x02\0\0.\x03\x03.*\x16\x03\x03\0\x0b\x0c\0\0\x07\0\x05steam
        options: s
      product: Valve Steam In-Home Streaming service
      info: TLSv1.2 PSK
    - name: ssl
      pattern:
        regex: ^\x16\x03[\0-\x03]..\x02\0\0.\x03[\0-\x03].*\x16\x03[\0-\x03]\0.\x0c.....(.+?)(?:\x16\x03[\0-\x03]|$)
        options: s
      product: TLS PSK
      info: 'PSK identity hint: $P(1)'
    - name: ssl
      pattern:
        regex: ^\x15\x03[\0-\x04]\0\x02[\x01\x02].$
        options: s
