name: svrloc
protocol: udp
rarity: 8
payload: \x02\x01\x00\x006 \x00\x00\x00\x00\x00\x01\x00\x02en\x00\x00\x00\x15service:service-agent\x00\x07default\x00\x00\x00\x00
ports: "427"
services:
    - name: svrloc
      pattern:
        regex: ^\x02\x0b
      product: Service Location Protocol
      version: "2"
