name: NetMotionMobility
protocol: udp
rarity: 7
payload: \0\x40\x50\0\0\0\0\x85\x5d\xb4\x91\x28\0\0\0\0\0\x01\x7c\x91\x40\0\0\0\xaa\x39\xda\x42\x37\x65\xcf\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0
ports: "5008"
services:
    - name: NetMotionMobility
      pattern:
        regex: ^\0\x40\x51\0\0\0\0
      product: NetMotion Mobility VPN
