name: pcworx
protocol: tcp
rarity: 9
payload: \x01\x01\x00\x1a\x00\x00\x00\x00x\x80\x00\x03\x00\x0cIBETH01N0_M\x00
ports: "1962"
services:
    - name: pcworx
      pattern:
        regex: \x81\x01\0\x14\0\0\0\x01\0\0\0\0\0\x02\0\0\0.\0\0
      product: Phoenix Contact PCWorx
